workspaces:

  dev:

    s3:
      - bkt_name: logs
        versioning: false
      
      - bkt_name: config

      - bkt_name: api.pix

      - bkt_name: app.compliance-monitoring-evidences
        versioning: false
        cors_rule: [
          {
            allowed_methods: ["PUT", "GET"],
            allowed_origins: ["https://dev.backoffice.safepag.com"],
            allowed_headers: ["*"],
            expose_headers: []
          }
        ]

      - bkt_name: app.cnab-files
        versioning: false

      - bkt_name: app.transaction-core-payment-manual-receipt
        versioning: false
        cors_rule: [
          {
            allowed_methods: ["PUT", "GET"],
            allowed_origins: ["*"],
            allowed_headers: ["*"],
            expose_headers: []
          }
        ]

      - bkt_name: app.transaction-core-file-report
        versioning: false
        cors_rule: [
          {
            allowed_methods: ["PUT", "GET"],
            allowed_origins: ["*"],
            allowed_headers: ["*"],
            expose_headers: []
          }
        ]

      - bkt_name: app.efx-remittance-batch-files
        cors_rule: [
          {
            allowed_methods: ["PUT", "GET"],
            allowed_origins: ["*"],
            allowed_headers: ["*"],
            expose_headers: []
          }
        ]

      - bkt_name: app.efx-remittance-files
        cors_rule: [
          {
            allowed_methods: ["PUT", "GET"],
            allowed_origins: ["*"],
            allowed_headers: ["*"],
            expose_headers: []
          }
        ]

    frontend:
      #- bkt_name: backoffice
      #- bkt_name: my
      #- bkt_name: checkout
      - bkt_name: teste

    alb:
      - name: private
        internal: true
        service:
          core:
            priority: 1
            health_check_path: /core/actuator/health
            health_check_interval: 300
            health_check_timeout: 120
            healthy_threshold_count: 3
            unhealthy_threshold_count: 3
          pix:
            priority: 2
            health_check_path: /pix/actuator/health
            health_check_interval: 300
            health_check_timeout: 5
            healthy_threshold_count: 3
            unhealthy_threshold_count: 3
          backoffice:
            priority: 3
            #health_check_path: /backoffice/actuator/health
            health_check_interval: 300
            health_check_timeout: 5
            healthy_threshold_count: 3
            unhealthy_threshold_count: 3

      - name: public
        internal: false
        service:
          gateway:
            priority: 1
            health_check_path: /gateway/actuator/health
            health_check_interval: 300
            health_check_timeout: 120
            healthy_threshold_count: 3
            unhealthy_threshold_count: 3

    ecs:
      - cluster: main
        service:
          core:
            cpu: 256
            memory: 512
            desired_count: 1
            autoscaling_max_capacity: 2
            environment: 
              - name: AWS_REGION
                value: sa-east-1
              - name: RABBIT_MQ_ENABLE_SSL
                value: true
              - name: SPRING_PROFILES_ACTIVE
                value: "${var.env}"
            secrets:
              - name: AWS_ACCESS_KEY
                valueFrom: service_aws_access_key_dev
              - name: AWS_SECRET_KEY
                valueFrom: service_aws_secret_key_dev
            mountPoints:
              - sourceVolume: DEV-DocumentDBCerts-EFS-dev
                containerPath: /etc/config-cert
          #pix:
          #backoffice: